[env]
build_flags =
    -Wno-unused-variable
    -Wno-unused-function   

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = cmsis
upload_protocol = stlink
debug_tool = stlink

build_flags =
    -D STM32F103xB